<?php

namespace Tests\Unit\Article;

use App\Services\Article\ArticleService;
use Tests\TestCase;

class ArticleServiceTest extends TestCase
{

    private $articleService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->articleService = new ArticleService();
    }

    /**
     * Проверяем метод сервиса,
     * возвращает количество статей пользователя за сутки
     *
     * @return void
     */
    public function test_count_day()
    {
        $createArticle = $this->articleService->countDayArticle('user');
        $this->assertIsInt($createArticle);
    }
}
